// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCRaQ-q2RkryyNaKHFWw16sVR5mhVix0o',
    appId: '1:884157981994:web:699d13175186ab8961aa53',
    messagingSenderId: '884157981994',
    projectId: 'mochi-manga',
    authDomain: 'mochi-manga.firebaseapp.com',
    storageBucket: 'mochi-manga.firebasestorage.app',
    measurementId: 'G-2SNTKHCGEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt8eElT3vDefmwByXZvvbY4fz7yQC1vTo',
    appId: '1:884157981994:android:4f4ffcbc0903761761aa53',
    messagingSenderId: '884157981994',
    projectId: 'mochi-manga',
    storageBucket: 'mochi-manga.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNYTrB_GYVH2bkhZsZzr4N6xJoCgI17Tg',
    appId: '1:884157981994:ios:1715063072fb4fea61aa53',
    messagingSenderId: '884157981994',
    projectId: 'mochi-manga',
    storageBucket: 'mochi-manga.firebasestorage.app',
    iosBundleId: 'com.example.mochi',
  );
}
